# Base Config

default_pipeline_queue: 'cpu-only'
default_task_queue: 'cpu-only'

controller:
  name: 'hydra_audio_preprocessing_pipeline'
  project: 'audio_preproc_test'
  version: '0.0.1'

stages:
  stage_standardizing:
    dataset_task_id: null
    input_filetype: '.flac'
    normalize: true
    channels: 1
    sample_rate: 16000

  stage_silence_splitting:
    min_silence_len: 500
    thresh: 16

  stage_audio_splitting:
    max_duration: 30000
    min_duration: 500

hydra:
  run:
    dir: '.'